### ISSUE TITLE
RouteSteps.calculateSteps returning empty

### ISSUE THREAD

**Issue by kgrigsby-codesmith** [johnpatrickmorgan/FlowStacks#18]
I have a use case where `routes = [.root(screen1), .push(screen2(X))]`. Then using:
```
 withDelaysIfUnsupported {
  $0.popToRoot()
  $0.push(.screen2(Y)
}
```
Notice the screen2's have different associated values. The problem is the screen didn't change. RouteSteps.calculateSteps returned an empty array.

I worked around it by: 
```
        routes.popToRoot()
        
        DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(650)) {
            self.routes.push(.screen2(Y))
        }
```

I suppose if the associated values were Equatable and additional check could be made in calculateSteps but that could be problematic if they're classes/ObservableObjects.

I think if there were another function that just executed the steps with delays that would work for me.

**Comment by johnpatrickmorgan** [comment]
Hi @kgrigsby-codesmith!

Thanks for raising this. I'd like to clarify some things please.

> I have a use case where routes = [.root(screen1), .push(screen2(X))]. 

Just to check - I assume your screens are embedded in a `NavigationView` somehow? 

> RouteSteps.calculateSteps returned an empty array

Is that right? I don't think `RouteSteps.calculateSteps` can ever return an empty array. In the case you described, I would expect it to return 1 step but not 0: I would expect it to return `[[.root(screen1), .push(screen2(Y))]]`, as we can jump straight to the desired state in a single state update. Unfortunately though, that would cause the screen to update without any push/pop animation, which might not be desired. Currently, the `withDelaysIfUnsupported` function is intended to sidestep SwiftUI's limitations of what kind of changes can be made to a navigation hierarchy in a single state update. In your use case, there is no change to the navigation hierarchy, only a change to the screen content, so the `withDelaysIfUnsupported` function won't introduce any delayed state updates. 

Aside: it would be good if we could use SwiftUI's transition modifier to animate switching the content of the top screen, but when I've experimented with that, the transition only seems to work for the root screen. So for now it updates withoput animation.

Am I right in thinking you want it to animate the pop and then animate the push? If so, perhaps a utility for scheduling a series of animation updates would help. Under the hood, `withDelaysIfUnsupported` uses a function to schedule a series of state updates with delays in between, so maybe exposing that functionality would be useful?

> The problem is the screen didn't change. RouteSteps.calculateSteps returned an empty array.

Having said all the above, that doesn't sound like the expected behaviour I've described, so maybe there's something else going on. Would you be able to provide an example to reproduce it please?

**Comment by kgrigsby-codesmith** [comment]
Upon further investigation today I figured out it's behaving the way you intended. (i.e. calculateSteps is returning [[.root(screen1), .push(screen2(Y))]] as you said), self.scheduleRemainingSteps was being passed an empty array because of the dropFirst. My UI isn't updating because I don't understand when state objects get recreated.It's not being recreated when screen2(Y) is being pushed.It looks like I need to use an ObservedObject in my view instead and pass it in with the new data.
