### ISSUE TITLE
Not updating the view after e.g. coverScreen or push

### ISSUE THREAD

**Issue by Kondamon** [johnpatrickmorgan/FlowStacks#39]
We have found out a strange behaviour that have occurred a few times now during implementation. We don't know if it's related to using multiple ObservableObjecs within the views and passing them around from the parent to a few childs or is it something else.

After a button click the routes are updated as expected but after the routes update e.g. via coverScreen, no rendering update happens in SwiftUI. So it looks like the if the button click doesn't have any effect on the UI. I have played around with using a custom .id(increasingNumber) on the related view and modified the id with the button click. After the 2nd click all buttons responds as expected again. However, do you have any idea why does this happen when using FlowStacks?

**Comment by Kondamon** [comment]
We have figured out the root cause of this issue. It is related to passing an ObservableObject with `Routes` from the parent to the child. Both hold the same instance of this object. However, this leads to not updating the view anymore when e.g. pushing a "view" to routes. is there any workaround for this issue?

```
class TabbarModel: ObservableObject {

    @Published var activeTab: MainTab = .tab1

    @Published var routes: Routes<TabbarCoordinator.Screen>

    init(routes: Routes<TabbarCoordinator.Screen> = [.root(.tab1(nil))]) {
        self.routes = routes
    }
    
}
```

**Comment by johnpatrickmorgan** [comment]
Hi @Kondamon!

```swift
// When you comment out the next line, everything works fine
model.routes = [.root(.home)]
```

This line is the problem. The `getModel() `  function is called whenever `ParentView`'s `body` is evaluated. It mutates the model's `routes` property, which causes the ParentView's body to be re-evaluated. This continues in an infinite loop.

Even without the infinite loop, you would be continually resetting the routes state to the beginning whenever you tried to present a new screen:
- Present a new screen by mutating ChildModel's routes.
- Causes ParentView's body to be re-evaluated, resetting the routes so that the presented screen is removed.

**Comment by Kondamon** [comment]
Thank you, this helped me to resolve that issue!
