### ISSUE TITLE
Inconsistent state of Routes variable after present/push when VC is presented on top (from UIKit)

### ISSUE THREAD

**Issue by Scvairy** [johnpatrickmorgan/FlowStacks#73]
I have an SDK that pushes (through UIKit) a fullscreen cover on app start, and I have my own cover, also on app start (ask for notifications).

If SDK presents its cover and then I present my - only SDK's cover is presented.
And when SDK's cover is dismissed, I see my root view, but I get an assertion failure: it tries to push view on top of "invisible" sheet that is not embedded into navigation view.
If I embed it into navigation view, then assert's not firing, but push doesn't work either.

Can I somehow forcely update the hierarchy after SDK's modal dismissal?
Or, maybe, synchronize routes array with actual state (if view wasn't presented, then it should disappear from (or not even be added to) routes array)

Thank you for your help!

**Comment by johnpatrickmorgan** [comment]
Thanks for raising this issue. Out of interest, which SDK is it? I don't see a good way to resolve the issue in this library, but I can see ways to work around the problem, such as:
- Using a different modality for 'presenting' your own screen on app start (not a sheet/cover) - e.g. conditionally showing the notifications screen or the main view from the app root, and using a `.transition()` modifier to animate the transition between them. Or using push navigation rather than cover presentation.
- Delaying initialising the SDK until after your own fullscreen cover is dismissed.
- Delaying your own fullscreen cover until after the SDK's has been dismissed (though I guess you might not know when that happens).

**Comment by Scvairy** [comment]
Thank you for your answer and your suggestions!

The SDK is DivPro: https://github.com/divkit/divkitpro/

I think I have another one option, from the SDK side:
I can write and inject own “presenter” (the sdk allows it) and wrap their UIViewController in SwiftUI view, and present it normally through FlowStacks.

I’ll try it out.

**Comment by johnpatrickmorgan** [comment]
Ah great, that would be ideal.
